### ISSUE TITLE
Faraday's Electromagnetic Lab main checklist

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#1]
NOTE: This checklist also includes these derivative sims:  
* **Magnet and Compass**
* **Magnets and Electromagnets**
* **Generator**

## Design

- [x] **Sim folder and design doc created** (Date: 04/03/2023)
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- [x] **Review user feedback**, see #8 
  - [x] *If a  Port:* [Google Form suggestions reviewed](https://docs.google.com/spreadsheets/d/1KkvutfIVwZLi5-jz_DVP3zC8jXkzF32-hzMI4ztB1uY/edit?resourcekey#gid=324007787&fvid=677625918)
  - [x] *If a new sim:* [Google Form suggestions reviewed](https://docs.google.com/spreadsheets/d/1KkvutfIVwZLi5-jz_DVP3zC8jXkzF32-hzMI4ztB1uY/edit?resourcekey#gid=324007787&fvid=898967246)
- [x] **Learning goals and standards identified** (Date: 04/05/2023)
- [x] **Design concept complete**  (Date: //)
-  ~~**Wireframes complete** (Date: //)~~
-  ~~**Mockups complete** (Date: //)~~
  - [x] Mockups checked for colorblind and greyscale
- [x] **Features for PhET-iO discussion**
- [x] **Interviews complete** (Date: 04/08/2024)
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: //)
  - [x] Performance acceptable, see #99 
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- ~~**Prototype items**~~
  - ~~Auxiliary screenshots (at least 1 additional)~~
  - ~~Accessories (keywords, categories, description, learning goals, related sims, NSDL) as appropriate~~
  - ~~Email/Twitter announcement language~~
  - ~~Teacher Guide created, uploaded, and added to sim design folder~~
  - ~~Send Simulation Notification from the Admin page (to alert translators)~~
- [x] **Pre-publication items**
  - [x] Auxiliary screenshots (up to 3 additional) - see #158 
  - [x] Screen-specific screenshots for metadata service (
    see [naming convention](https://github.com/phetsims/website/issues/1322#issuecomment-1010320827)) - see #158
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Accessibility features
  - [x] [Draft the Email announcement language](https://github.com/phetsims/tasks/issues/new?assignees=&labels=tasks%3Aemail&projects=&template=sim-announcement-email.md&title=Sim+Announcement+Email)
  - [x] Teacher Guide created, uploaded, and added to sim design folder - see #40 
  - [x] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each screen created and uploaded to Drive - see #159
  - [x] [LoL metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429) 
    for each screen (description, vocab words, questions for before/after sim use) - see #159
- [x] **Make sim visible on website**
  - [x] Clear "Metadata caches" on the [Basic Administration Caches](https://phet.colorado.edu/?wicket:bookmarkablePage=:edu.colorado.phet.website.admin.AdminCachesPage) page
- [x] **Post-publication items**
  - [x] *If a Port:* Review legacy gold star activities, copy over if appropriate
  - [ ] Share new features, design challenges, and treats with group!
  - [x] Email announcement
  - [x] Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) - see #159 
  - [x] Create "sim primer" issue - https://github.com/phetsims/faradays-electromagnetic-lab/issues/205
  - ~~Hold postmortem if applicable (Date: //)~~
  - [x] Send Simulation Notification from the Admin page (to alert translators)

## Inclusive Features

- [x] Alternative Input (Started: 10/23/23) (Completed: 1/23/24) - see https://github.com/phetsims/faradays-electromagnetic-lab/issues/14
- [x] Sound & Sonification (UI) - see https://github.com/phetsims/faradays-electromagnetic-lab/issues/15
- ~~Sound & Sonification (Pedagogical)~~ - ([sonification design document](https://docs.google.com/document/d/1IoQX0ybxgxso57yedPZB8NvkWuMLMBD71kO04k7hZHo/edit#heading=h.qxxnnmfrpx3k)) Note: Attempted sonification, but did not complete.
  - ~~Sound design complete (Started: ) (Completed: )~~
  - ~~Development complete (Started: ) (Completed: )~~
- ~~Interactive Description - (link to description design & implementation checklist)~~
  -  ~~Description design complete (Started: ) (Completed: )~~
  - ~~Development complete (Started: ) (Completed: )~~
  - ~~Mobile description included~~
- ~~Voicing - (include links to relevant voicing design document)~~

## Implementation

- [x] **Repository created** by following [new-repo-checklist.md](https://github.com/phetsims/phet-info/blob/main/checklists/new-repo-checklist.md) (Date: 10/27/23)
- [x] **Development started** (Date: 10/30/23)
- [x] **Sim is "feature complete"** (Date: 1/9/24) ***at 87 hours***
- [x] **QA team "first look"** (Date: 3/4/24)
- [ ] ~~**Sim team sign-off** (Date: //)~~
- [x] **Code review completed** (Date: 3/28/24)
- [x] **Sim dev test completed** (Date: 6/10/24, 7/18/24)
- [x] **Sim RC tests completed** (Date: 7/29/24)
- [x] **Pre-publication items**
  - [x] Main screenshot (read [this](https://github.com/phetsims/QA/blob/main/documentation/qa-book.md#screenshots))
  - [x] Verify credits
  - [ ] ~~Add CT tests for public query parameters that need testing. See examples
    in [listContinuousTests.js](https://github.com/phetsims/perennial/blob/main/js/listContinuousTests.js)~~
- [x] **Published** (Date: 7/29/24) ***at ~355 hours***

## QA

-  ~~*If a Port:* **Legacy sim tested for bugs**; issues reported in repo~~
- [x] **Dev testing started** (Date: 5/30/2024)
- [x] **Dev testing completed** (Date: 7/18/2024)
- [x] **First RC published** (Date: 7/18/2024)
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: 7/29/2024)

**Comment by pixelzoom** [comment]
Assigning to @arouinfar and @KatieWoe to complete the Design and QA sections above.  Last one assigned please close this issue.

**Comment by arouinfar** [comment]
Checklist completed using dates from https://github.com/phetsims/faradays-electromagnetic-lab/issues/18, closing.
