### ISSUE TITLE
Teacher Tips

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-electromagnetic-lab#40]
This issue will capture things that should be included in teacher tips.

**Comment by pixelzoom** [comment]
- [x] Per https://github.com/phetsims/faradays-electromagnetic-lab/issues/30#issuecomment-1877833000, include something about the direction of electrons vs the direction of conventional current, see also #136

**Comment by arouinfar** [comment]
- [x] Using alt input to move the magnet at a constant speed, #25 
- [x] Query Parameters/Preferences:
  - [x] #23 
  - [x] #24 
  - [x] #27 
- [x] Compass needle behavior, including the immediate alignment when B >= 10 G, https://github.com/phetsims/faradays-electromagnetic-lab/issues/67
- [x] There is no resistance in the model. #117, #118, #119

**Comment by pixelzoom** [comment]
- [x] `generator.turbine.dragFactorProperty` is used to simulate drag ("back EMF") on the turbine caused by the pickup coil.  Discussed more in https://github.com/phetsims/faradays-electromagnetic-lab/issues/11.

**Comment by pixelzoom** [comment]
- [x] In https://github.com/phetsims/faradays-electromagnetic-lab/issues/10#issuecomment-1960548641, @kathy-phet noted:

>  I noticed that the field meter has a similar issue in that it appears to be "in front" of the magnet and electromagnet, but measures the inside of it. I currently has exactly the behavior of the Java sim and as I thought through what would happen if it was in the "same layer" as the compass that seemed more problematic than not. So I guess for the teacher tips, just note that it is "magical" and "measuring in the center plane" or something like that?

**Comment by arouinfar** [comment]
FEL Teacher Tips are complete, but may need minor revision as we get closer to publication. I'm holding off on the derivative sims to avoid propagating changes across multiple documents.

**Comment by arouinfar** [comment]
I decided to finish up the remaining Teacher Tips documents. Remaining TODOS:

- [x] Add query parameter and info for #136 
- [x] Power Supply panels are draggable #163 
- [x] Calibration is optimized on a screen-by-screen basis #174 
- [x] Re-take screenshots if there are any visual changes
- [x] Test all links to ensure they work (requires sims to be deployed to production)
- [x] Upload final .pages and .pdf files to [Sharepoint folder](https://o365coloradoedu.sharepoint.com/sites/PHYS-phet-pilot/PhET%20Files/Forms/AllItems.aspx?id=%2Fsites%2FPHYS%2Dphet%2Dpilot%2FPhET%20Files%2FPhET%20Files%2FPhET%20Sim%20Design%2FFaraday%27s%20Electromagnetic%20Lab%20Suite%20HTML5)
- [x] Upload .pdf to the website

**Comment by arouinfar** [comment]
I've updated the Teacher Tips for all sims in the suite. The remaining TODOs in https://github.com/phetsims/faradays-electromagnetic-lab/issues/40#issuecomment-2010259858 will be addressed once the sims are published.

**Comment by pixelzoom** [comment]
1.0.0 has been published for all 4 sims in the suite, so this issue can resume.

**Comment by arouinfar** [comment]
The Teacher Tips have been uploaded to the website, closing.
